// Authenticate User
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADING = 'USER_LOADING';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

// Login/Logout User
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Register User
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// Add/Remove/Update Project
export const ADD_PROJECT_START = 'ADD_PROJECT_START';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL';

export const REMOVE_PROJECT_START = 'REMOVE_PROJECT_START';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';
export const REMOVE_PROJECT_FAIL = 'REMOVE_PROJECT_FAIL';

export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

// Add/Remove/Update Tribe
export const ADD_TRIBE_START = 'ADD_TRIBE_START';
export const ADD_TRIBE_SUCCESS = 'ADD_TRIBE_SUCCESS';
export const ADD_TRIBE_FAIL = 'ADD_TRIBE_FAIL';

export const REMOVE_TRIBE_START = 'REMOVE_TRIBE_START';
export const REMOVE_TRIBE_SUCCESS = 'REMOVE_TRIBE_SUCCESS';
export const REMOVE_TRIBE_FAIL = 'REMOVE_TRIBE_FAIL';

export const UPDATE_TRIBE_START = 'UPDATE_TRIBE_START';
export const UPDATE_TRIBE_SUCCESS = 'UPDATE_TRIBE_SUCCESS';
export const UPDATE_TRIBE_FAIL = 'UPDATE_TRIBE_FAIL';
=======
// Errors
export const GET_ERRORS = 'GET_ERRORS';
